(ns ndcalc.state-test
  (:require [cljs.test :refer-macros [deftest is use-fixtures]]
            [ndcalc.engine :as e]
            [ndcalc.demo :as demo]
            [ndcalc.state :as s]))

(use-fixtures :each
  {:before #(do (remove-watch s/app :persist)
                (reset! s/app {:route :editor :doc (demo/blank-document "test" 5) :view :plane
                               :mode :normal :undo [] :redo [] :viewport [-1 -1] :grid-size [8 12]}))
   :after #(when @s/toast-timer (js/clearTimeout @s/toast-timer))})

(deftest navigation-preserves-inactive-dimensions
  (s/select! [-1 -2 3 4 5] false)
  (s/move! 1 -1 false)
  (is (= [0 -3 3 4 5] (s/coord)))
  (s/switch! 3)
  (s/move! 1 1 false)
  (is (= [0 -2 4 4 5] (s/coord)))
  (s/switch! 3)
  (is (= [3 0] (s/mapping)))
  (s/move! 1 10 false)
  (is (= [0 -2 5 4 5] (s/coord))))

(deftest safe-coordinate-boundaries
  (s/jump! 0 js/Number.MAX_SAFE_INTEGER)
  (is (= js/Number.MAX_SAFE_INTEGER (first (s/coord))))
  (is (<= (+ (first (:viewport @s/app)) 7) js/Number.MAX_SAFE_INTEGER))
  (s/move! 1 0 false)
  (is (= js/Number.MAX_SAFE_INTEGER (first (s/coord))))
  (s/jump! 0 (- js/Number.MAX_SAFE_INTEGER))
  (is (= (- js/Number.MAX_SAFE_INTEGER) (first (:viewport @s/app))))
  (s/move! -1 0 false)
  (is (= (- js/Number.MAX_SAFE_INTEGER) (first (s/coord)))))

(deftest visual-selection-and-function-fill
  (s/select! [-2 -3 1 0 0] false)
  (s/toggle-visual!)
  (s/move! 1 1 false)
  (is (= 4 (count (s/selected-coords))))
  (s/open-editor! "formula")
  (swap! s/app assoc-in [:editor :source] "(a,b,...rest) => a+b+rest[0]")
  (s/save-editor!)
  (is (= :normal (:mode @s/app)))
  (is (= 4 (count (get-in @s/app [:doc :cells]))))
  (is (= -4 (:value ((:evaluate (s/runtime)) [-2 -3 1 0 0])))))

(deftest null-and-named-selections
  (s/select! ["plain"] false)
  (s/toggle-visual!)
  (is (nil? (:anchor @s/app)))
  (is (= [["plain"]] (s/selected-coords)))
  (s/move! 1 0 false)
  (is (= [0 0 0 0 0] (s/coord)))
  (s/set-mapping! 0 0)
  (s/set-mapping! 1 0)
  (s/move! 100 100 true)
  (is (= [[0 0 0 0 0]] (s/selected-coords)))
  (s/switch! 1)
  (is (= [0 0 0 0 0] (:anchor @s/app)))
  (is (= :visual (:mode @s/app))))

(deftest five-dimensional-visual-fill-survives-plane-switches
  (s/select! [-2 -3 0 0 0] false)
  (s/toggle-visual!)
  (s/move! 1 1 false)
  (doseq [dimension [3 4 5]]
    (s/switch! dimension)
    (s/move! 0 (if (= dimension 4) -1 1) false))
  (s/set-mapping! 0 1)
  (is (= :visual (:mode @s/app)))
  (is (= [-2 -3 0 0 0] (:anchor @s/app)))
  (is (= 32 (count (s/selected-coords))))
  (let [coords (s/selected-coords)]
    (s/open-editor! "formula")
    (is (= 32 (count (get-in @s/app [:editor :coords]))))
    (swap! s/app assoc-in [:editor :source] "(a,b,c,d,e) => a+b+c+d+e")
    (s/save-editor!)
    (is (= 32 (count (get-in @s/app [:doc :cells]))))
    (doseq [c coords] (is (= (reduce + c) (:value ((:evaluate (s/runtime)) c))))))
  (is (= :normal (:mode @s/app)))
  (is (nil? (:anchor @s/app)))
  (s/undo! false)
  (is (empty? (get-in @s/app [:doc :cells])))
  (s/undo! true)
  (is (= 32 (count (get-in @s/app [:doc :cells])))))

(deftest slice-inputs-and-preview-preserve-hyperbox-selection
  (swap! s/app assoc :cube-axes [1 2 3])
  (s/toggle-visual!)
  (s/move! 1 1 false)
  (s/set-slice! 3 -1)
  (is (= 8 (count (s/selected-coords))))
  (is (= [0 0 0 0 0] (:anchor @s/app)))
  (s/toggle-3d!)
  (s/toggle-3d!)
  (is (= :visual (:mode @s/app)))
  (is (= 8 (count (s/selected-coords))))
  (s/set-mapping! 0 0)
  (s/set-mapping! 1 0)
  (is (= 8 (count (s/selected-coords)))))

(deftest hyperbox-clear-and-selection-limit
  (s/change! #(-> %
                  (e/put-cell ["keep"] {:kind "value" :source "42"})
                  (e/put-cell [4 4 4] {:kind "value" :source "99"})))
  (s/toggle-visual!)
  (s/select! [1 1 1 0 0] false)
  (s/open-editor! "value")
  (swap! s/app assoc-in [:editor :source] "7")
  (s/save-editor!)
  (s/select! [0 0 0 0 0] false)
  (s/toggle-visual!)
  (s/select! [1 1 1 0 0] false)
  (s/switch! 3)
  (s/clear!)
  (is (= {"[4,4,4,0,0]" {:kind "value" :source "99"}} (get-in @s/app [:doc :cells])))
  (is (= "42" (:source (e/cell-at (:doc @s/app) ["keep"]))))
  (s/toggle-visual!)
  (s/select! [9 9 9 9 9] false)
  (let [before (:doc @s/app)]
    (s/open-editor! "value")
    (s/clear!)
    (is (nil? (:editor @s/app)))
    (is (= before (:doc @s/app)))
    (is (= :visual (:mode @s/app)))))

(deftest hyperbox-clipboard-keeps-depth-and-plane-orientation
  (let [source {:kind "formula" :source "(a,b,c) => a+10*b+100*c"}]
    (s/change! #(-> % (e/put-cell [-1 -2 0] source) (e/put-cell [0 0 1] source)
                       (e/put-cell [11 20 30 7 -8] {:kind "value" :source "99"})))
    (s/select! [0 0 1 0 0] false)
    (s/toggle-visual!)
    (s/select! [-1 -2 0 0 0] false)
    (s/yank!)
    (is (= [2 3 2 1 1] (get-in @s/app [:clipboard :shape])))
    (is (= 12 (count (get-in @s/app [:clipboard :cells]))))
    (s/set-mapping! 0 3)
    (s/set-mapping! 1 1)
    (s/select! [10 20 30 7 -8] false)
    (s/paste!)
    (is (= source (e/cell-at (:doc @s/app) [10 20 30 7 -8])))
    (is (= source (e/cell-at (:doc @s/app) [12 21 31 7 -8])))
    (is (nil? (e/cell-at (:doc @s/app) [11 20 30 7 -8])))
    (is (= 3322 (:value ((:evaluate (s/runtime)) [12 21 31 7 -8]))))
    (s/open-document! (demo/blank-document "2D target" 2))
    (s/paste!)
    (is (empty? (get-in @s/app [:doc :cells])))
    (s/select! ["keep"] false)
    (s/paste!)
    (is (empty? (get-in @s/app [:doc :named])))))

(deftest axis-clear-stays-in-the-current-slice
  (s/change! #(-> %
                  (e/put-cell [0 0] {:kind "value" :source "1"})
                  (e/put-cell [0 1] {:kind "value" :source "2"})
                  (e/put-cell [1 1] {:kind "value" :source "3"})
                  (e/put-cell [0 1 1] {:kind "value" :source "4"})))
  (s/clear-axis! 0)
  (is (nil? (e/cell-at (:doc @s/app) [0 0])))
  (is (nil? (e/cell-at (:doc @s/app) [0 1])))
  (is (= "3" (:source (e/cell-at (:doc @s/app) [1 1]))))
  (is (= "4" (:source (e/cell-at (:doc @s/app) [0 1 1]))))
  (s/undo! false)
  (is (= 4 (count (get-in @s/app [:doc :cells])))))

(deftest configurable-volume-fit-and-depth-navigation
  (s/open-document! (demo/color-document))
  (s/toggle-3d!)
  (is (= [8 8 8] (:shape (s/cube-window))))
  (is (= 512 (:total (s/cube-window))))
  (is (:cube-fit @s/app))
  (s/move-depth! 1)
  (is (= [0 0 4] (s/coord)))
  (is (= [0 0 0] (:start (s/cube-window))))
  (s/set-cube-size! 0 4)
  (is (false? (:cube-fit @s/app)))
  (is (= [4 8 8] (:shape (s/cube-window))))
  (is (= [-1 -3 1] (:start (s/cube-window))))
  (s/set-cube-option! :zoom 125)
  (s/fit-cube!)
  (is (= 125 (:zoom (s/cube-options))))
  (is (= 512 (:total (s/cube-window)))))

(deftest oversized-previews-never-change-the-document-or-window
  (swap! s/app assoc :cube-axes [1 2 3])
  (s/set-cube-option! :size [16 16 16])
  (let [doc (:doc @s/app)]
    (s/set-cube-size! 0 32)
    (is (= [16 16 16] (:size (s/cube-options))))
    (is (= doc (:doc @s/app)))
    (is (re-find #"4096" (:toast @s/app)))))

(deftest shrinking-rank-repairs-the-preview-z-axis
  (swap! s/app assoc :cube-axes [1 2 5])
  (s/change! #(e/resize-dimensions % 3))
  (s/toggle-3d!)
  (is (= [1 2 3] (:cube-axes @s/app)))
  (is (= 512 (:total (s/cube-window)))))

(deftest cube-axes-and-navigation-stay-in-sync
  (swap! s/app assoc :cube-axes [1 2 3])
  (s/toggle-3d!)
  (s/switch! 1)
  (is (= [2 3 1] (:cube-axes @s/app)))
  (s/move! 1 1 false)
  (is (= [0 1 1 0 0] (s/coord)))
  (s/set-cube-axis! 2 2)
  (is (= [1 3 2] (:cube-axes @s/app)))
  (is (= [1 3] (s/mapping)))
  (s/switch! 3)
  (is (= :cube (:view @s/app)))
  (is (= [1 2 3] (:cube-axes @s/app)))
  (is (= [1 2] (s/mapping))))

(deftest dimension-matched-formula-templates
  (doseq [[n expected] [[0 "(...rest) => "] [1 "(a,...rest) => "]
                        [2 "(a,b,...rest) => "] [3 "(a,b,c,...rest) => "]
                        [5 "(a,b,c,d,e,...rest) => "]]]
    (is (= expected (s/formula-template n false))))
  (is (= "(name,...rest) => " (s/formula-template 5 true)))
  (is (fn? (e/compile-expression (str (s/formula-template 32 false) "0") nil)))
  (s/open-editor! "formula")
  (is (= "(a,b,c,d,e,...rest) => " (get-in @s/app [:editor :source])))
  (is (true? (get-in @s/app [:editor :focus-source])))
  (swap! s/app assoc :editor nil)
  (s/open-editor! nil)
  (s/set-editor-kind! "formula")
  (is (= "(a,b,c,d,e,...rest) => " (get-in @s/app [:editor :source])))
  (swap! s/app assoc-in [:editor :source] "x => 42")
  (s/set-editor-kind! "value")
  (s/set-editor-kind! "formula")
  (is (= "x => 42" (get-in @s/app [:editor :source])))
  (s/new-named!)
  (s/set-editor-kind! "formula")
  (is (= "(name,...rest) => " (get-in @s/app [:editor :source]))))

(deftest existing-sources-are-not-replaced-by-templates
  (let [source "(a,b,...rest) => 42"]
    (s/change! #(e/put-cell % [] {:kind "formula" :source source}))
    (s/open-editor! nil)
    (is (= source (get-in @s/app [:editor :source]))))
  (s/change! #(e/put-cell % [] {:kind "value" :source "123"}))
  (s/open-editor! "formula")
  (is (= "123" (get-in @s/app [:editor :source]))))

(deftest editing-formatting-rules-keeps-identity-and-order
  (let [rule {:id "first" :name "Original" :enabled true :coord "() => true" :value "v => ['base']"}
        other {:id "second" :name "Other" :enabled true :coord "() => false" :value "v => []"}
        edited (assoc rule :name "Edited" :enabled false :coord "(a,b) => b === 0" :value "v => 'color: coral'")]
    (s/change! #(assoc % :rules [rule other]))
    (s/open-rule! rule)
    (swap! s/app assoc :rule-editor edited)
    (s/save-rule!)
    (is (= [edited other] (get-in @s/app [:doc :rules])))
    (is (nil? (:rule-editor @s/app)))
    (s/undo! false)
    (is (= [rule other] (get-in @s/app [:doc :rules])))
    (s/undo! true)
    (is (= [edited other] (get-in @s/app [:doc :rules])))
    (let [before (:doc @s/app)]
      (s/open-rule! edited)
      (swap! s/app assoc-in [:rule-editor :coord] "(()")
      (s/save-rule!)
      (is (= before (:doc @s/app)))
      (is (string? (get-in @s/app [:rule-editor :error]))))))

(deftest cube-supports-edit-fill-clear-copy-paste-and-undo
  (s/toggle-3d!)
  (s/toggle-visual!)
  (s/move! 1 1 false)
  (s/move-depth! 1)
  (is (= 8 (count (s/selected-coords))))
  (s/open-editor! "formula")
  (swap! s/app assoc-in [:editor :source] "(a,b,c) => a+b+c")
  (s/save-editor!)
  (is (= :cube (:view @s/app)))
  (is (= 8 (count (get-in @s/app [:doc :cells]))))
  (is (= 3 (:value ((:evaluate (s/runtime)) [1 1 1]))))
  (s/undo! false)
  (is (empty? (get-in @s/app [:doc :cells])))
  (s/undo! true)
  (is (= 8 (count (get-in @s/app [:doc :cells]))))
  (s/yank!)
  (s/select! [2 2 2 0 0] false)
  (s/paste!)
  (is (= 6 (:value ((:evaluate (s/runtime)) [2 2 2]))))
  (s/clear!)
  (is (nil? (e/cell-at (:doc @s/app) [2 2 2])))
  (s/undo! false)
  (s/clear-axis! 0)
  (is (nil? (e/cell-at (:doc @s/app) [2 2 2])))
  (s/new-named!)
  (swap! s/app update :editor assoc :name "cube input" :source "42")
  (s/save-editor!)
  (s/select! ["cube input"] false)
  (s/open-editor! nil)
  (swap! s/app assoc-in [:editor :source] "84")
  (s/save-editor!)
  (is (= "cube input" (:named-focus @s/app)))
  (is (= "84" (:source (e/cell-at (:doc @s/app) ["cube input"]))))
  (s/open-rule! nil)
  (s/save-rule!)
  (is (= 1 (count (get-in @s/app [:doc :rules])))))

(deftest cube-clipboard-orients-all-three-view-axes
  (s/toggle-3d!) (s/toggle-visual!)
  (s/select! [1 2 3 0 0] false)
  (s/open-editor! "formula")
  (swap! s/app assoc-in [:editor :source] "(a,b,c,d,e) => [a,b,c,d,e]")
  (s/save-editor!)
  (s/toggle-visual!) (s/select! [0 0 0 0 0] false) (s/yank!)
  (is (= [2 3 4 1 1] (get-in @s/app [:clipboard :shape])))
  (s/set-cube-axes! [4 5 2])
  (s/select! [10 20 30 40 50] false) (s/paste!)
  (is (= 48 (count (get-in @s/app [:doc :cells]))))
  (is (= [10 23 30 41 52] (js->clj (:value ((:evaluate (s/runtime)) [10 23 30 41 52])))))
  (is (nil? (e/cell-at (:doc @s/app) [10 24 30 41 52])))
  (is (nil? (e/cell-at (:doc @s/app) [10 23 31 41 52]))))

(deftest cube-dimension-queue-preserves-point-and-selection
  (s/select! [-1 2 3 4 5] false)
  (s/toggle-3d!) (s/toggle-visual!) (s/move-depth! 1)
  (let [c (s/coord) anchor (:anchor @s/app)]
    (doseq [[dimension expected] [[3 [1 2 3]] [1 [2 3 1]] [1 [2 3 1]] [2 [3 1 2]]
                                [4 [1 2 4]] [0 [1 2 4]] [5 [2 4 5]] [4 [2 5 4]]]]
      (s/switch! dimension)
      (is (= expected (:cube-axes @s/app)))
      (is (= (vec (take 2 expected)) (s/mapping)))
      (is (= :cube (:view @s/app)))
      (is (= c (s/coord)))
      (is (= anchor (:anchor @s/app)))
      (is (= :visual (:mode @s/app))))))

(deftest undo-and-dimension-resizing-keep-valid-volume-axes
  (s/toggle-3d!)
  (s/change! #(e/resize-dimensions % 6))
  (s/switch! 6)
  (s/undo! false)
  (is (= :cube (:view @s/app)))
  (is (= [1 2 3] (:cube-axes @s/app)))
  (s/change! #(e/resize-dimensions % 2))
  (is (= :plane (:view @s/app))))
